// <auto-generated />
namespace EFFluentAPI.FluentAPIMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SetRelationShipTableCoursesTableCoverOneToOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetRelationShipTableCoursesTableCoverOneToOne));
        
        string IMigrationMetadata.Id
        {
            get { return "202008232017251_SetRelationShipTableCoursesTableCoverOneToOne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
